ALTER TYPE "RetailerAccountStatus" ADD VALUE IF NOT EXISTS 'DEACTIVATED';

ALTER TABLE "RetailerProfile"
ADD COLUMN IF NOT EXISTS "lastActivityAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "deactivatedAt" TIMESTAMP(3);
